### ISSUE TITLE
initialization of ES index lost

### ISSUE THREAD

**Issue by svigerske** [scipopt/rubberband#64]
"small changes" in b06fc5fe45 disabled the commands to initialize and purge the ElasticSearch index, so the steps
```
bin/rubberband-ctl create-index
bin/rubberband-ctl populate-index
```
from the README.md do not work anymore.

What was the reason to remove these (@fschloesser)? And should they be added again?

**Comment by fschloesser** [comment]
I don't remember why this was committed, and not just a local change.
I imagine that I tested out some things and wanted to be sure not to break things too badly on my local database. Feel free to enable those functions again.

**Comment by svigerske** [comment]
OK, I reenabled the commands in a5d2b9490493d75c59fdada7d0d91f814a21eccc and disabled your new commands that seemed to be rather for debugging in 74c38f9f6bdbe0a82004ba42c0fac1399528ceb5. Most other changes from b06fc5fe seem to be intended. That it adds ipet evaluations with eval files that are not part of this repo should be handled in #66.
